version: '3'
services:          
    frontend:
        build: .     
        container_name: textsum_frontend_arm64
        ports:
            - "80:80"
        volumes: 
            - ./:/frontend
            - /frontend/node_modules