version: '3.9'
services: 
    backend:
        image: textsum_endpoint_arm64
        build: 
            context: ./backend
            dockerfile: Dockerfile
            
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000
        container_name: textsum_endpoint_arm64
        ports:
            - "8000:8000"

    frontend:
        build: 
            context: ./frontend
            dockerfile: Dockerfile.dev
        command: npm start
        container_name: textsum_frontend_dev_arm64
        ports:
            - "3000:3000"
        restart: on-failure
        depends_on:
            - backend