version: '3.9'
services: 
    frontend:
        build:
            context: ./frontend/textsum
            dockerfile: Dockerfile
        container_name: textsum_frontend
        ports:
            - "80:80"
        volumes: 
            - ./:/frontend
            - /frontend/node_modules 

    backend:
        image: textsum_endpoint
        build: 
            context: .
            dockerfile: Dockerfile
            
        command: uvicorn app.text_sum_endpoint:app --host 0.0.0.0 --port 8000
        container_name: textsum_endpoint
        ports:
            - "8000:8000"
