version: '3'
services:          
    backend:
        build:
            context: .
            dockerfile: Dockerfile
            
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000
        container_name: textsum_endpoint
        ports:
            - "8000:8000"