version: '3'
services: 
    frontend:
        build: 
            context: .
            dockerfile: Dockerfile
        command: npm start
        container_name: textsum_frontend
        ports:
            - "3000:3000"        
