version: '3'
services: 
    frontend:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        command: npm start
        container_name: textsum_frontend_dev
        ports:
            - "3000:3000"        
